services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Maro@2024
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

  redis:
    image: redis

  web:
    build: .
    command: ["puma", "-C", "config/puma.rb"]
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: Maro@2024

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
